# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('char_value', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'global_values',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='decoration',
            field=models.IntegerField(blank=True, choices=[(1, 'None'), (2, 'Simple'), (3, 'Complex'), (4, 'Very complex')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
