# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-10 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20170309_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flavor2',
            new_name='flavor',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size2',
            new_name='size',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('category', 'flavor', 'size')]),
        ),
    ]
