# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-16 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20180516_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_whole_wheat',
            new_name='is_whole_grain',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('category', 'flavor', 'size', 'is_sugar_free', 'is_whole_grain')]),
        ),
    ]
