# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-17 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20180516_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='size',
            name='short_name',
        ),
    ]
