# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20160908_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
