# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-08 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.IntegerField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/flavors/')),
            ],
            options={
                'db_table': 'flavor',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.IntegerField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/sizes/')),
            ],
            options={
                'db_table': 'size',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Category'),
        ),
        migrations.AddField(
            model_name='flavor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Flavor'),
        ),
        migrations.AddField(
            model_name='product',
            name='size2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Size'),
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together=set([('category', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='flavor',
            unique_together=set([('category', 'name')]),
        ),
    ]
