# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-09 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20170308_1248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([]),
        ),
    ]
