# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-11 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20170310_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
