# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20170311_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/backgrounds/')),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'background',
            },
        ),
    ]
