# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-16 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20180511_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sugar_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_whole_wheat',
            field=models.BooleanField(default=False),
        ),
    ]
