version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
# aqui poner para development (copiar los de deploy)
      # - SECRET_KEY=
      # - SENDINBLUE_KEY=
      # - ALLOWED_HOSTS=127.0.0.1,localhost
      # - DATABASE_NAME=
      # - DATABASE_USERNAME=
      # - DATABASE_PASSWORD=
      # - DATABASE_HOST=host.docker.internal
